# Generated by Django 6.0.4 on 2026-04-12 17:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_record_options_record_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-created_at'], 'verbose_name': 'customer record', 'verbose_name_plural': 'customer records'},
        ),
        migrations.AlterField(
            model_name='record',
            name='address',
            field=models.CharField(help_text='Street address or P.O. box.', max_length=100, verbose_name='street address'),
        ),
        migrations.AlterField(
            model_name='record',
            name='city',
            field=models.CharField(help_text='City or locality.', max_length=50, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='record',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the record was first created.', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(help_text="Customer's primary email address.", max_length=100, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='record',
            name='first_name',
            field=models.CharField(help_text="Customer's first (given) name.", max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='record',
            name='last_name',
            field=models.CharField(help_text="Customer's last (family) name.", max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone',
            field=models.CharField(help_text="Customer's phone number (7–15 digits, optional leading '+').", max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be 7–15 digits, optionally starting with '+'.", regex='^\\+?\\d{7,15}$')], verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.CharField(help_text='State, province, or region.', max_length=50, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='record',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the record was last modified.', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='record',
            name='zipcode',
            field=models.CharField(help_text='ZIP or postal code.', max_length=20, verbose_name='ZIP / postal code'),
        ),
    ]
